{
	"version": 1739155968,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/swap-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/particles.png",
		"images/tiledbackground.png",
		"images/money-sheet0.png",
		"images/greg-sheet0.png",
		"media/slime.m4a",
		"media/0825.m4a",
		"media/0825.ogg",
		"media/2.m4a",
		"media/2.ogg",
		"media/swap.m4a",
		"media/swap.ogg",
		"media/pose.m4a",
		"media/pose.ogg",
		"media/reverse secret.m4a",
		"media/reverse secret.ogg",
		"media/2 reversed.m4a",
		"media/2 reversed.ogg",
		"media/reversed.m4a",
		"media/reversed.ogg",
		"media/pose reversed.m4a",
		"media/pose reversed.ogg",
		"media/lover.m4a",
		"media/lover.ogg",
		"media/hero.m4a",
		"media/hero.ogg",
		"media/dream.m4a",
		"media/dream.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-256.png",
		"loading-logo.png",
		"icon-114.png",
		"icon-128.png"
	]
}